import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle} from 'react-icons/ai';
import {AiFillLinkedin} from "react-icons/ai";
import {AiFillYoutube} from "react-icons/ai";
import Image from 'next/legacy/image';
import devren from '../public/renne_spacesuit1.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from "../public/consulting.png";
import pipe from '../public/pipe.webp';
import power from "../public/Power-BI-Logo-transparent.png";
import power1 from "../public/powerbi project 1.png";
import power2 from "../public/powerbi project 2.png";
import power3 from "../public/powerbi project 3.png";
import aws1 from "../public/aws_arch1.jpg";
import ELT1 from "../public/ELT-Solution.png";
import {useState} from "react";
import {useEffect} from 'react';



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Renne Botchway's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">
              developedbyrenné
            </h1>
            <ul className="flex items-center dark:text-white">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-cyan-400 font-medium md:text-6xl">
              Renné Botchway
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Data Analyst/ Cloud Architect/ Data Pipeline
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-l mx-auto dark:text-white">
              A highly motivated and experienced technologist with a passion for
              using technology to solve problems beyond Earth. I am proficient
              in a variety of tools and techniques. I am confident that I can
              make a significant contribution to your organization's mission to
              explore the unknown. If you are interested in taking your problems
              to new heights, do contact me.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-150 h-150 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={devren} layout="" objectFit="cover" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">What I do</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              Since working as an analyst and architect I have done work for
              <span className="text-teal-500"> agencies</span>, consulted for{" "}
              <span className="text text-teal-500"> companies </span> and
              coloborated with talented people to create digital solutions for
              businesses.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">Data Analytics</h3>
              <p className="py-2">
                Indepth data analytics, data wrangling and data visualization
                with the aim of making data beautiful & driving organisational
                objectives.
              </p>
              <h4 className="py-4 text-teal-600">Analytics tools I use</h4>
              <p className="text-gray-800 py-1">PowerBi</p>
              <p className="text-gray-800 py-1">Excel</p>
              <p className="text-gray-800 py-1">Looker</p>
              <p className="text-gray-800 py-1">Tableau</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Cloud Architecture
              </h3>
              <p className="py-2">
                Design and implement scalable, secure, and cost-effective cloud
                solutions using predominantly on Amazon Web Services (AWS) .
              </p>
              <h4 className="py-4 text-teal-600">Cloud tools I use</h4>
              <p className="text-gray-800 py-1">AWS</p>
              <p className="text-gray-800 py-1">Docker</p>
              <p className="text-gray-800 py-1">BigQuery</p>
              <p className="text-gray-800 py-1">Terraform</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={pipe} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">Data Pipeline</h3>
              <p className="py-2">
                Automated processes that will efficiently and reliably move data
                from source, ensuring transformation & load to a target
                destination for analysis.
              </p>
              <h4 className="py-4 text-teal-600">Pipelines tools I use</h4>
              <p className="text-gray-800 py-1">DBT</p>
              <p className="text-gray-800 py-1">FiveTran</p>
              <p className="text-gray-800 py-1">Snowflake</p>
              <p className="text-gray-800 py-1">SQL Server</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              Since working as an analyst and architect I have done work for
              <span className="text-teal-500"> agencies</span>, consulted for{" "}
              <span className="text text-teal-500"> companies </span> and
              coloborated with talented people to create digital solutions for
              businesses.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={power1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={aws1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={ELT1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
